-- Migration: Create logs table for Agent Audit System
-- Requirements: 9.1, 9.2, 9.3, 9.4, 9.5

-- Create logs table with all required columns
CREATE TABLE IF NOT EXISTS logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    query TEXT NOT NULL,
    response TEXT NOT NULL,
    audit JSONB NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('Safe', 'Warning', 'Flagged'))
);

-- Create index on created_at for efficient time-based queries (descending order for recent logs)
CREATE INDEX IF NOT EXISTS idx_logs_created_at ON logs(created_at DESC);

-- Create index on status for filtering by risk status
CREATE INDEX IF NOT EXISTS idx_logs_status ON logs(status);

-- Create index on risk_score extracted from JSONB audit column for efficient risk-based queries
CREATE INDEX IF NOT EXISTS idx_logs_risk_score ON logs((audit->>'risk_score')::int);

-- Add comment to table for documentation
COMMENT ON TABLE logs IS 'Stores audit logs for AI agent queries, responses, and risk assessments';

-- Add comments to columns for documentation
COMMENT ON COLUMN logs.id IS 'Unique identifier for each audit log entry';
COMMENT ON COLUMN logs.created_at IS 'Timestamp when the audit log was created';
COMMENT ON COLUMN logs.query IS 'User query sent to the worker agent';
COMMENT ON COLUMN logs.response IS 'Response generated by the worker agent';
COMMENT ON COLUMN logs.audit IS 'JSON object containing audit results from the auditor agent';
COMMENT ON COLUMN logs.status IS 'Risk status classification: Safe (0-3), Warning (4-6), or Flagged (7-10)';
